/**********************************************************************************************************************
 * \file Appscheduling.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "AppScheduling.h"
#include "Driver_Stm.h"

#include "Platform_Types.h"
#include "GTM_TOM_PWM.h"
#include <math.h>
#include "LPF.h"
#include "adc.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define CH_A                    &MODULE_P14,0
#define CH_B                    &MODULE_P14,1
#define LOW_VAL                 0
#define HIGH_VAL                1

#define PI                      3.141592
#define TICKS_PER_REVOLUTION    48
#define Ts                      0.001
#define Kp                      0.5
#define Ki                      0.1     // 0.005
#define Kd                      0.8
#define PWM_Period              50000       // (uint16 : 0~65535)

#define CUT_OFF_FREQ            100
/*********************************************************************************************************************/
/*------------------------------------------------------Typedef-------------------------------------------------------*/
/*********************************************************************************************************************/
typedef struct
{
    uint32 u32nuCnt1ms;
    uint32 u32nuCnt10ms;
    uint32 u32nuCnt100ms;
    uint32 u32nuCnt1000ms;
    uint32 u32nuCnt5000ms;
}TestCnt;
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
sint32 Encoder_Ticks = 0;
sint32 prev_Encoder_Ticks = 0;

double radiansPerTick = 0.0;  // 한 틱당 라디안
double totalRadians = 0.0;    // 총 라디안
double speedRadPerSec = 0.0;     // 초당 라디안
double Rad_per_Sec = 0.0;
double Rad_per_Sec_prev = 0.0;
double Rad_per_Origin_prev = 0.0;

uint8 time_s = 0;
uint32 Vin = 0;
double error_w = 0.0f;
double error_w_int = 0.0f;
double error_w_old = 0.0f;
double error_w_int_old = 0.0f;
double w_ref = 0.0f;
double w = 0.0f;

uint16 V_reg = 0;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
TestCnt stTestCnt;
uint8 _tmp = 0;
uint8 prev_CHA = 0;
uint8 prev_CHB = 0;
double in_Rads = 0;


/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void AppTask1ms(void);
static void AppTask10ms(void);
static void AppTask100ms(void);
static void AppTask1000ms(void);
static void AppTask5000ms(void);

void AppNoTask(void);
double calculateSpeed_Rads(sint64 encoderTicks, double deltaTime);
uint32 Make_Pulse_Generate(uint8 _t, double w_ref, double w);
uint32 Make_Pulse_as_Vreg(double w_ref, double w);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

static void AppTask1ms(void){
    stTestCnt.u32nuCnt1ms++;

    Rad_per_Sec = calculateSpeed_Rads(Encoder_Ticks - prev_Encoder_Ticks, Ts); // rad/s 구하기
    Rad_per_Origin_prev = Rad_per_Sec;

//    Encoder_Ticks = 0; // 초기화.

//    if(time_s <= 4) in_Rads = 0;
//    else if(time_s > 4 && time_s <= 19) in_Rads = (double)((time_s - 4) * (626/15));
//    else if(time_s > 19 && time_s <= 26) in_Rads = (double)626.2;
//    else if(time_s > 26 && time_s <= 41) in_Rads = (double)((41 - time_s) * (626/15));

    V_reg = getAdc(&SAR4_7);
    in_Rads = (double)(V_reg * 626 / 4096);

    Rad_per_Sec = LPF(Rad_per_Origin_prev, Rad_per_Sec_prev, Ts, CUT_OFF_FREQ); // LPF(저역통과 필터 적용) 통과.

//    Vin = Make_Pulse_Generate(time_s, in_Rads, Rad_per_Sec);
    Vin = Make_Pulse_as_Vreg(in_Rads, Rad_per_Sec);
    setDutyCycle((uint16)(Vin *(PWM_Period/11)));

    prev_Encoder_Ticks = Encoder_Ticks;
    Rad_per_Sec_prev = Rad_per_Sec;
}
static void AppTask10ms(void){
    stTestCnt.u32nuCnt10ms++;
}
static void AppTask100ms(void){
    stTestCnt.u32nuCnt100ms++;
//    IfxPort_togglePin(&MODULE_P10,1);
}
static void AppTask1000ms(void){
    stTestCnt.u32nuCnt1000ms++;
    time_s++;
}
static void AppTask5000ms(void){
    stTestCnt.u32nuCnt5000ms++;

    /*if(_tmp ^= 1) setDutyCycle(50000);
    else setDutyCycle(20000);*/

}

void AppScheduling(void){
    AppNoTask();

    if(stSchedulingInfo.u8nuScheduling1msFlag == 1u){
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();

        if(stSchedulingInfo.u8nuScheduling10msFlag == 1u){
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if(stSchedulingInfo.u8nuScheduling100msFlag == 1u){
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }

        if(stSchedulingInfo.u8nuScheduling1000msFlag == 1u){
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }

        if(stSchedulingInfo.u8nuScheduling5000msFlag == 1u){
            stSchedulingInfo.u8nuScheduling5000msFlag = 0u;
            AppTask5000ms();
        }
    }

}

void AppNoTask(){
    uint8 CH_A_cur_val = IfxPort_getPinState(CH_A);
    uint8 CH_B_cur_val = IfxPort_getPinState(CH_B);

    // Encoder Tick counting
    if(prev_CHA != CH_A_cur_val){
        if(CH_A_cur_val == HIGH_VAL){
            Encoder_Ticks = CH_B_cur_val ? Encoder_Ticks-1 : Encoder_Ticks+1;
            /*if(CH_B_cur_val == LOW_VAL){
                Encoder_Ticks++;
            }
            else if(CH_B_cur_val == HIGH_VAL){
                Encoder_Ticks--;
            }*/
        }
        else if(CH_A_cur_val == LOW_VAL){
            Encoder_Ticks = CH_B_cur_val ? Encoder_Ticks+1 : Encoder_Ticks-1;
            /*if(CH_B_cur_val == HIGH_VAL){
                Encoder_Ticks++;
            }
            else if(CH_B_cur_val == LOW_VAL){
                Encoder_Ticks--;
            }*/
        }
    }

    if(prev_CHB != CH_B_cur_val){
        if(CH_B_cur_val == HIGH_VAL){
            Encoder_Ticks = CH_A_cur_val ? Encoder_Ticks+1 : Encoder_Ticks-1;
            /*if(CH_A_cur_val == HIGH_VAL){
                Encoder_Ticks++;
            }
            else if(CH_A_cur_val == LOW_VAL){
                Encoder_Ticks--;
            }*/
        }
        else if(CH_B_cur_val == LOW_VAL){
            Encoder_Ticks = CH_A_cur_val ? Encoder_Ticks-1 : Encoder_Ticks+1;
            /*if(CH_A_cur_val == LOW_VAL){
                Encoder_Ticks++;
            }
            else if(CH_A_cur_val == HIGH_VAL){
                Encoder_Ticks--;
            }*/
        }
    }

    prev_CHA = CH_A_cur_val;
    prev_CHB = CH_B_cur_val;

    return;
}

void Encoder_Two_Channel_Init(){
    IfxPort_setPinModeInput(CH_A, IfxPort_InputMode_pullUp);
    IfxPort_setPinModeInput(CH_B, IfxPort_InputMode_pullUp);
}

double calculateSpeed_Rads(sint64 encoderTicks, double deltaTime) {
    if(encoderTicks < 0) encoderTicks = -encoderTicks;

    double radiansPerTick = 2 * PI / TICKS_PER_REVOLUTION;  // 한 틱당 라디안
    double totalRadians = encoderTicks * radiansPerTick;    // 총 라디안
    double speedRadPerSec = totalRadians / deltaTime;       // 초당 라디안

//    speedRadPerSec = (speedRadPerSec < 0) ? (-speedRadPerSec) : speedRadPerSec;
    return speedRadPerSec;
}

uint32 Make_Pulse_Generate(uint8 _t, double w_ref, double w){
    if(_t <= 4){
        Vin = 0;
    }
    else if(_t > 4 && _t <= 41){
        error_w = w_ref - w; // w_ref : 입력한 rad/s 값. w : 실제 모터의 rad/s
        error_w_int = error_w_int_old + (error_w)*Ts;
        error_w_int_old = error_w_int;

        float derivative = error_w - error_w_old;

        if(error_w_int > 10) error_w_int = 10;

        Vin = (Kp*error_w + Ki*error_w_int + Kd*derivative);    // PID제어
//        Vin = (Kp*error_w + Ki*error_w_int);    // PI제어

        if(Vin > 11) Vin = 11;
        else if(Vin < 0) Vin = 0;

        error_w_old = error_w;
    }
    else if(_t > 41){
        Vin = 0;
    }
    return Vin;
}

uint32 Make_Pulse_as_Vreg(double w_ref, double w){

    error_w = w_ref - w; // w_ref : 입력한 rad/s 값. w : 실제 모터의 rad/s
    error_w_int = error_w_int_old + (error_w)*Ts;
    error_w_int_old = error_w_int;

    float derivative = error_w - error_w_old;

    if(error_w_int > 10) error_w_int = 10;

    Vin = (Kp*error_w + Ki*error_w_int + Kd*derivative);    // PID제어
//        Vin = (Kp*error_w + Ki*error_w_int);    // PI제어

    if(Vin > 11) Vin = 11;
    else if(Vin < 0) Vin = 0;

    error_w_old = error_w;

    return Vin;
}
