/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxGtm_PinMap.h"

#include "GTM_TOM_PWM.h"
#include "Bsp.h"

#include "LED.h"
#include "Driver_Stm.h"
#include "Appscheduling.h"


#include "math.h"
#include "adc.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define WAIT_TIME   10              /* Number of milliseconds to wait between each duty cycle change                */

IfxCpu_syncEvent g_cpuSyncEvent = 0;
//uint16 a0 = 0u;

void core0_main(void)
{
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
        
//    unsigned char c;
//    _init_uart3();

    LED_Init();
    Driver_Stm_Init();  // 시스템 타이머 모듈 초기화.
    Encoder_Two_Channel_Init(); // 엔코더 채널 핀 초기 설정.

    IfxCpu_enableInterrupts();

    /* Initialize a time variable */
   Ifx_TickTime ticksFor10ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, WAIT_TIME);

   /* Initialize GTM TOM module */
   initGtmTomPwm();

   initAdc(&SAR4_7);
   Init_Ultrasonic();
    while(1)
    {
        float32 d = Get_Ultrasonic_Distance();

        /*c = _in_uart3(); // 문자 입력
        _out_uart3(c); // 입력받은 문자열 다시 전송
        if(c == '\r'){
            _out_uart3('\n'); // 개행 문자 처리
        }*/

        //AppScheduling(); // 앱 스케쥴링 실행.
//        a0 = getAdc(&SAR4_7);

//        fadeLED();                  /* Change the intensity of the LED  */
//        setDutyCycle(5000);
//        waitTime(ticksFor10ms * 500);     /* Delay of 10ms                    */
//        setDutyCycle(0);
        //waitTime(ticksFor10ms);     /* Delay of 10ms                    */
    }
}
