/**********************************************************************************************************************
 * \file Vadc.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Vadc.h"
#include "IfxVadc.h"
#include "IfxVadc_Adc.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Typedef-------------------------------------------------------*/
/*********************************************************************************************************************/
typedef struct
{
    IfxVadc_Adc vadc;
    IfxVadc_Adc_Group adcGroup;
}App_VadcAutoScan;

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
App_VadcAutoScan g_VadcAutoScan;

IfxVadc_Adc_Channel adc0Channel[ADC_GROUP0_MAX];

SensorAdcRaw stSensorAdcRaw;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void DrvAdc_Group0Init(void);
static void DrvAdc_Group0ChannelInit(uint8 param_ChNum);


/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
voidDrvAdcInit(void){
    DrvAdc_Group0Init();
}

static void DrvAdc_Group0Init(void){
    /* VADC 구현 */


    IfxVadc_Adc_Config adcConfig;                                         /* Define a configuration structure         */
    IfxVadc_Adc_initModuleConfig(&adcConfig, &MODULE_VADC);               /* Fill it with default values              */

    /* initailize module */
    IfxVadc_Adc_initModule(&g_VadcAutoScan, &adcConfig);                          /* Apply the configuration                  */

    /*create group config */
    IfxVadc_Adc_GroupConfig adcGroupConfig;                               /* Define a configuration structure         */
    IfxVadc_Adc_initGroupConfig(&adcGroupConfig, &g_VadcAutoScan.vadc);                /* Fill it with default values              */

    adcGroupConfig.groupId = IfxVadc_GroupId_0;                           /* Select the Group 4                       */
    adcGroupConfig.master = adcGroupConfig.groupId;                         /* Set the same group as master group       */

    /* Enable the background scan source and the background auto scan functionality */
    adcGroupConfig.arbiter.requestSlotBackgroundScanEnabled = TRUE;

    /* Enable auto sacn */
    adcGroupConfig.scanRequest.autoscanEnabled = TRUE;

    /* Enable the gate in "always" mode (no edge detection) */
    adcGroupConfig.scanRequest.triggerConfig.gatingMode = 1;

    IfxVadc_Adc_initGroup(&g_VadcAutoScan.adcGroup, &adcGroupConfig);                 /* Apply the configuration                  */

    /* 사용자 채널 초기화 */
    DrvAdc_Group0ChannelInit(ADC_GROUP0_CH1);
    DrvAdc_Group0ChannelInit(ADC_GROUP0_CH2);
    DrvAdc_Group0ChannelInit(ADC_GROUP0_CH3);

    /* start autoscan */
    IfxVadc_Adc_startScan(&g_VadcAutoScan.adcGroup);
}

static void DrvAdc_Group0ChannelInit(uint8 param_ChNum){
    IfxVadc_Adc_ChannelConfig adcChannelConfigInfo;             /* Array of configuration structures        */
    uint32 ulTemp = ((uint32)1u << param_ChNum);

    IfxVadc_Adc_initChannelConfig(&adcChannelConfigInfo, &g_VadcAutoScan.adcGroup);

    adcChannelConfigInfo.channelId       = (IfxVadc_ChannelId)(param_ChNum);
    adcChannelConfigInfo.resultRegister  = (IfxVadc_ChannelResult)(param_ChNum);

    /* initialize the channel */
    IfxVadc_Adc_initChannel(&adc0Channel[param_ChNum], &adcChannelConfigInfo);

    /* add to sacn */
    IfxVadc_Adc_setScan(&g_VadcAutoScan.adcGroup, ulTemp, ulTemp);
}

/* ----------------------- Test Code --------------- */
void DrvAdc_GetAdcRawGroup0(void){
    Ifx_VADC_RES conversionResult;

    /* Get Data*/
    conversionResult = IfxVadc_Adc_getResult(&adc0Channel[ADC_GROUP0_CH1]);
    stSensorAdcRaw.UlSSense1_Raw = conversionResult.B.RESULT;
    conversionResult = IfxVadc_Adc_getResult(&adc0Channel[ADC_GROUP0_CH2]);
    stSensorAdcRaw.UlSSense2_Raw = conversionResult.B.RESULT;
    conversionResult = IfxVadc_Adc_getResult(&adc0Channel[ADC_GROUP0_CH3]);
    stSensorAdcRaw.UlSSense3_Raw = conversionResult.B.RESULT;

    /* Start Autosacn */
    IfxVadc_Adc_startScan(&g_VadcAutoScan.adcGroup);
}
